version: '2'
services:
  walle-db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    container_name: walle-db
    command: [
       "--log-bin=mysql-bin",
       "--server-id=1",
       "--character-set-server=utf8",
       "--collation-server=utf8_general_ci",
       "--innodb_flush_log_at_trx_commit=1",
       "--sync_binlog=1"
       ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: walle
      MYSQL_USER: walle
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306

  walle:
    image: walle:2.0
    restart: always
    hostname: walle.tfit.com
    container_name: walle
    ports:
      - 80:80
    depends_on:
      - walle-db
    tty: true
    command: bash -c "nginx && python /opt/walle/waller.py"
    volumes:
      - ./key_ssh:/root/.ssh
      - ./src/settings_prod.py:/opt/walle/walle/config/settings_prod.py
      - ./src/walle.conf:/etc/nginx/conf.d/walle.conf
      - ./src/waller.py:/opt/walle/waller.py

