version: '2'
services:
  walle-db:
    image: mysql:5.7
    volumes:
      - /opt/walle_2.0/db_data:/var/lib/mysql
    restart: always
    container_name: walle-db
    command: [
       "--log-bin=mysql-bin",
       "--server-id=1",
       "--character-set-server=utf8",
       "--collation-server=utf8_general_ci",
       "--innodb_flush_log_at_trx_commit=1",
       "--sync_binlog=1"
       ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: walle
      MYSQL_USER: walle
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      sys_net:
        ipv4_address: 172.168.88.210
    extra_hosts:
      - "openldap:172.168.88.239"

  walle:
    image: walle:2.0
    restart: always
    hostname: wd.tfit.com
    container_name: walle
    networks:
      sys_net:
        ipv4_address: 172.168.88.209
    depends_on:
      - walle-db
    tty: true
    command: bash -c "nginx && python /opt/walle/waller.py"
    volumes:
      - /opt/walle_2.0/key_ssh:/root/.ssh
      - /opt/walle_2.0/src/settings_prod.py:/opt/walle/walle/config/settings_prod.py
      - /opt/walle_2.0/src/walle.conf:/etc/nginx/conf.d/walle.conf
      - /opt/walle_2.0/src/nginx.conf:/etc/nginx/nginx.conf
      - /opt/walle_2.0/src/waller.py:/opt/walle/waller.py
    extra_hosts:
      - "openldap:172.168.88.239"

networks:
  sys_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.168.88.0/24
          gateway: 172.168.88.1
